# ------------------------------------------------Global Paths------------------------------------------------#
model2path:
  bge_m3: "/mnt/share/wwt/retriever_model/bge-m3"
  qwen2_5_7b_instruct: "/mnt/share/wwt/Qwen2.5-7B-Instruct"

model2pooling:
  bge_m3: "cls"

# ------------------------------------------------Environment Settings------------------------------------------------#
data_dir: "dataset/"
save_dir: "output/"

gpu_id: "0"
dataset_name: "prediction"
split: [ "test" ]

seed: 2024
save_intermediate_data: True

# -------------------------------------------------Retrieval Settings------------------------------------------------#
retrieval_method: "bge_m3"
index_path: "corpus/bge_m3_flat.index" 
corpus_path: "corpus/corpus.jsonl" 

retrieval_topk: 3
retrieval_batch_size: 64
retrieval_use_fp16: True
retrieval_query_max_length: 512

# -------------------------------------------------Generator Settings------------------------------------------------#
framework: "vllm"
generator_model: "qwen2_5_7b_instruct"
generator_max_input_len: 4096
generation_params:
  do_sample: False
  max_tokens: 512

vllm_kwargs:
  gpu_memory_utilization: 0.65
  tensor_parallel_size: 1
  dtype: "bfloat16"

# -------------------------------------------------Evaluation Settings------------------------------------------------#
metrics: ['acc', 'em']
save_metric_score: True